### ISSUE TITLE
Link your thesis and code to DeepXDE website

### ISSUE THREAD

**Issue by lululxvi** [mariusmerkle/TL-PINNs#3]
Hi Marius,

Great work. Do you want to add your thesis to DeepXDE website https://deepxde.readthedocs.io/en/latest/user/research.html , and maybe also with the link to your github code?

**Comment by mariusmerkle** [comment]
Hi Lu,

Thank you! Of course, I’d love to. How do we proceed?

**Comment by lululxvi** [comment]
You can go to DeepXDE repo, and make a pull request by modifying https://github.com/lululxvi/deepxde/blob/master/docs/user/research.rst

Or you can also send me the citation format and I can help you add it.
